/*Template generated by WebStorm on Saturday (7/22/23), 4:59 AM.
 * Author: kramstyles
 * Filename: LoadMore.jsx
 */

const LoadMore = ({ disabled = false, click }) => {
  return (
    <div className="d-grid">
      <button
        className="btn btn-dark p-4 shadow fs-10 fw-bold"
        disabled={disabled}
        onClick={click}
        style={{ 
          minHeight: '60px',
          transition: 'all 0.3s ease',
          opacity: disabled ? 0.6 : 1
        }}
      >
        {disabled ? 'Loading...' : 'Load More'}
      </button>
    </div>
  );
};

export default LoadMore;
